/* Generated by the CMS build step. The built-in practice details the
   runtime swaps out when the practice saves new ones in the dashboard. */
window.CMS_SITE = {
 "name": "Coastal Dental",
 "defaults": {
  "phone": "(02) 4306 7053",
  "tel": "0243067053",
  "email": "info@coastaldental.com.au",
  "address1": "12 Baker Street",
  "address2": "Gosford NSW 2250",
  "hours": [
   {
    "day": "Monday",
    "time": "7.30am \u2013 5.00pm"
   },
   {
    "day": "Tuesday",
    "time": "7.30am \u2013 6.30pm"
   },
   {
    "day": "Wednesday",
    "time": "7.30am \u2013 5.00pm"
   },
   {
    "day": "Thursday",
    "time": "9.00am \u2013 6.00pm"
   },
   {
    "day": "Friday",
    "time": "9.00am \u2013 5.00pm"
   },
   {
    "day": "Saturday",
    "time": "8.30am \u2013 4.00pm"
   },
   {
    "day": "Sunday",
    "time": "Closed"
   }
  ],
  "bookingUrl": "https://www.centaurportal.com/d4w/org-1916/search?practiceID=2125&shortVer=true&sourceID=null",
  "funds": [
   {
    "name": "Afterpay",
    "logo": "assets/img/J7GI3Yi.png"
   },
   {
    "name": "HICAPS \u2014 fast claims on the spot",
    "logo": "assets/img/XaA1HmB.png"
   },
   {
    "name": "DentiCare Payment Solutions",
    "logo": "assets/img/VRDXbb7.png"
   },
   {
    "name": "CBHS Health Fund",
    "logo": "assets/img/CxgQJOD.png"
   },
   {
    "name": "Medicare Child Dental Benefits Schedule",
    "logo": "assets/img/u3QcG5l.png"
   },
   {
    "name": "HCF \u2014 More for Teeth program",
    "logo": "assets/img/EDRlZdp.png"
   },
   {
    "name": "Bupa Members First",
    "logo": "assets/img/YW5LB0W.png"
   }
  ],
  "fundsCount": 7
 }
};
